import { useEffect, useMemo, useState } from 'react';
import { Boxes, Factory, Plus, Save, ShieldCheck, Trash2 } from 'lucide-react';
import { api } from './api';
import { SearchSelect } from './SearchSelect';
import './bomProduction.css';

type Company={id:string;workspace_id:string;name:string};
type Location={id:string;company_id:string;name:string;location_type:string};
type Item={id:string;code:string;name:string;category_name:string;category_type:string;base_unit_id:string;base_unit_code:string;track_stock:boolean;can_sell:boolean;can_produce:boolean;can_use_in_recipe:boolean};
type Unit={id:string;code:string;name:string;decimal_precision:number};
type Context={workspaceId:string;items:Item[];units:Unit[]};
type BomLine={id?:string;key:string;component_item_id?:string;componentItemId:string;component_code?:string;component_name?:string;quantity:string;unit_id?:string;unitId:string;unit_code?:string;waste_percent?:string;wastePercent:string;notes?:string|null};
type Bom={id:string;bom_type:'MENU'|'PRODUCTION';output_item_id:string;output_quantity:string;output_unit_id:string;version:number;status:string;notes:string|null;output_item_code:string;output_item_name:string;output_unit_code:string;lines:Array<Record<string,unknown>>};
type ProductionRow={id:string;transaction_number:string;transaction_date:string;location_name:string;notes:string|null;workflow_status:string;accounting_status:string;grand_total:string;negative_stock_override:boolean;batch_count:string;standard_output:string;actual_output:string;yield_percent:string;output_item_code:string;output_item_name:string;output_unit_code:string};
type Preview={shortages:Array<{itemName:string;available:string;requested:string;after:string;baseUnitCode:string}>;estimatedCost:string;production:{batch_count:string;standard_output:string;actual_output:string;yield_percent:string}|null};

const today=()=>new Date().toISOString().slice(0,10);
const money=(value:string|number)=>Number(value||0).toLocaleString('id-ID',{maximumFractionDigits:0});
const qty=(value:string|number)=>Number(value||0).toLocaleString('id-ID',{maximumFractionDigits:4});
const makeLine=():BomLine=>({key:crypto.randomUUID(),componentItemId:'',quantity:'1',unitId:'',wastePercent:'0'});

export function ClientBomProduction({canVerify,canOverride}:{canVerify:boolean;canOverride:boolean}){
  const [companies,setCompanies]=useState<Company[]>([]);const [locations,setLocations]=useState<Location[]>([]);const [companyId,setCompanyId]=useState('');const [context,setContext]=useState<Context|null>(null);
  const [boms,setBoms]=useState<Bom[]>([]);const [bomType,setBomType]=useState<'MENU'|'PRODUCTION'>('MENU');const [outputItemId,setOutputItemId]=useState('');const [outputQuantity,setOutputQuantity]=useState('1');const [outputUnitId,setOutputUnitId]=useState('');const [bomNotes,setBomNotes]=useState('');const [lines,setLines]=useState<BomLine[]>([makeLine()]);
  const [locationId,setLocationId]=useState('');const [productionBomId,setProductionBomId]=useState('');const [productionDate,setProductionDate]=useState(today());const [batchCount,setBatchCount]=useState('1');const [actualOutput,setActualOutput]=useState('');const [productionNotes,setProductionNotes]=useState('');const [productions,setProductions]=useState<ProductionRow[]>([]);
  const [saving,setSaving]=useState(false);const [verifying,setVerifying]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');

  const company=companies.find(x=>x.id===companyId);const companyLocations=locations.filter(x=>x.company_id===companyId);const activeBoms=boms.filter(x=>x.status==='ACTIVE'&&x.bom_type===bomType);const productionBoms=boms.filter(x=>x.status==='ACTIVE'&&x.bom_type==='PRODUCTION');
  const itemOptions=(context?.items||[]).map(x=>({id:x.id,label:`${x.code} — ${x.name}`,meta:x.category_name}));
  const outputOptions=(context?.items||[]).filter(x=>bomType==='MENU'?x.can_sell:(x.can_produce&&x.track_stock)).map(x=>({id:x.id,label:`${x.code} — ${x.name}`,meta:x.category_name}));

  async function loadBase(){const [c,l]=await Promise.all([api<Company[]>('/api/master/companies'),api<Location[]>('/api/master/locations')]);setCompanies(c);setLocations(l);if(!companyId&&c[0])setCompanyId(c[0].id);}
  async function loadCompany(){if(!companyId)return;const [ctx,bs,ps]=await Promise.all([api<Context>(`/api/client-transactions/bom-context?companyId=${companyId}`),api<Bom[]>(`/api/client-transactions/boms?companyId=${companyId}`),api<ProductionRow[]>(`/api/client-transactions/productions?companyId=${companyId}`)]);setContext(ctx);setBoms(bs);setProductions(ps);setLocationId(current=>companyLocations.some(x=>x.id===current)?current:(companyLocations[0]?.id||''));}
  useEffect(()=>{void loadBase();},[]);useEffect(()=>{void loadCompany();},[companyId,locations.length]);

  function chooseOutput(id:string){setOutputItemId(id);const item=context?.items.find(x=>x.id===id);setOutputUnitId(item?.base_unit_id||'');}
  function patchLine(key:string,patch:Partial<BomLine>){setLines(rows=>rows.map(row=>row.key===key?{...row,...patch}:row));}
  function chooseComponent(line:BomLine,id:string){const item=context?.items.find(x=>x.id===id);patchLine(line.key,{componentItemId:id,unitId:item?.base_unit_id||line.unitId});}
  function resetBom(){setOutputItemId('');setOutputQuantity('1');setOutputUnitId('');setBomNotes('');setLines([makeLine()]);}
  function editBom(bom:Bom){setBomType(bom.bom_type);setOutputItemId(bom.output_item_id);setOutputQuantity(bom.output_quantity);setOutputUnitId(bom.output_unit_id);setBomNotes(bom.notes||'');setLines(bom.lines.map((raw:any)=>({key:raw.id||crypto.randomUUID(),componentItemId:raw.component_item_id,quantity:String(raw.quantity),unitId:raw.unit_id,wastePercent:String(raw.waste_percent||0),notes:raw.notes||''})));window.scrollTo({top:0,behavior:'smooth'});}

  async function saveBom(){setError('');setMessage('');if(!companyId||!outputItemId||!outputUnitId||!lines.length)return setError('Output dan minimal satu bahan BOM wajib diisi.');if(lines.some(x=>!x.componentItemId||!x.unitId||Number(x.quantity)<=0))return setError('Lengkapi seluruh baris bahan BOM.');setSaving(true);try{const r=await api<{id:string;version:number}>('/api/client-transactions/boms',{method:'POST',body:JSON.stringify({companyId,bomType,outputItemId,outputQuantity:Number(outputQuantity),outputUnitId,notes:bomNotes||null,lines:lines.map(x=>({componentItemId:x.componentItemId,quantity:Number(x.quantity),unitId:x.unitId,wastePercent:Number(x.wastePercent||0),notes:x.notes||null}))})});setMessage(`BOM tersimpan sebagai versi ${r.version}.`);resetBom();await loadCompany();}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan BOM');}finally{setSaving(false);}}
  async function deactivateBom(id:string){if(!window.confirm('Nonaktifkan BOM ini? Riwayat transaksi produksi tetap tersimpan.'))return;try{await api(`/api/client-transactions/boms/${id}`,{method:'DELETE'});setMessage('BOM dinonaktifkan.');await loadCompany();}catch(e){setError(e instanceof Error?e.message:'Gagal menonaktifkan BOM');}}

  const selectedProductionBom=productionBoms.find(x=>x.id===productionBomId);const standardEntered=selectedProductionBom?Number(selectedProductionBom.output_quantity||0)*Number(batchCount||0):0;const yieldPreview=standardEntered>0&&Number(actualOutput)>0?Number(actualOutput)/standardEntered*100:0;
  async function saveProduction(){setError('');setMessage('');if(!companyId||!locationId||!productionBomId||Number(batchCount)<=0||Number(actualOutput)<=0)return setError('Lokasi, BOM, batch dan hasil aktual wajib diisi.');setSaving(true);try{const r=await api<{transaction_number:string;yieldPercent:string}>('/api/client-transactions/productions',{method:'POST',body:JSON.stringify({companyId,locationId,bomId:productionBomId,transactionDate:productionDate,batchCount:Number(batchCount),actualOutput:Number(actualOutput),notes:productionNotes||null})});setMessage(`${r.transaction_number} tersimpan sebagai draft. Yield ${Number(r.yieldPercent).toLocaleString('id-ID',{maximumFractionDigits:2})}%.`);setActualOutput('');setProductionNotes('');await loadCompany();}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan produksi');}finally{setSaving(false);}}
  async function verifyProduction(row:ProductionRow){setError('');setMessage('');setVerifying(row.id);try{const preview=await api<Preview>(`/api/client-transactions/productions/${row.id}/preview`);let allowBelowZero=false;if(preview.shortages.length){if(!canOverride){setError('Stok bahan tidak cukup. User ini tidak memiliki hak override stok minus.');return;}const details=preview.shortages.slice(0,8).map(x=>`${x.itemName}: tersedia ${qty(x.available)} ${x.baseUnitCode}, butuh ${qty(x.requested)}`).join('\n');allowBelowZero=window.confirm(`Stok bahan akan minus:\n${details}\n\nTetap Finance Verified?`);if(!allowBelowZero)return;}const result=await api<{totalCost:string;unitCost:string}>(`/api/client-transactions/productions/${row.id}/verify`,{method:'POST',body:JSON.stringify({allowBelowZero})});setMessage(`Finance Verified. Biaya produksi Rp${money(result.totalCost)}, HPP hasil produksi Rp${money(result.unitCost)} per satuan dasar.`);await loadCompany();}catch(e){setError(e instanceof Error?e.message:'Gagal Finance Verified produksi');}finally{setVerifying('');}}

  return <div className="page-content bom-production-page">
    {message&&<div className="form-success">{message}</div>}{error&&<div className="form-error">{error}</div>}
    <section className="section-card">
      <div className="section-title master-heading"><div><span className="eyebrow">BOM / RESEP</span><h3>Bill of Material</h3><p>BOM Menu untuk pemakaian bahan dari penjualan dan BOM Produksi untuk bahan setengah jadi / hasil produksi.</p></div><button className="primary-button compact" disabled={saving} onClick={saveBom}><Save size={16}/>{saving?'Menyimpan...':'Simpan BOM'}</button></div>
      <div className="bom-company-row"><label>Company<select value={companyId} onChange={e=>setCompanyId(e.target.value)}>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="bom-type-switch"><button className={bomType==='MENU'?'active':''} onClick={()=>{setBomType('MENU');resetBom();}}>BOM Menu</button><button className={bomType==='PRODUCTION'?'active':''} onClick={()=>{setBomType('PRODUCTION');resetBom();}}>BOM Produksi / STJ</button></div></div>
      <div className="bom-header-grid"><label>Output / Menu<SearchSelect value={outputItemId} options={outputOptions} placeholder={bomType==='MENU'?'Pilih menu jual...':'Pilih barang hasil produksi...'} onChange={chooseOutput}/></label><label>Hasil Standar<input type="number" min="0" step="0.000001" value={outputQuantity} onChange={e=>setOutputQuantity(e.target.value)}/></label><label>Satuan Output<select value={outputUnitId} onChange={e=>setOutputUnitId(e.target.value)}><option value="">Pilih satuan</option>{(context?.units||[]).map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select></label><label>Catatan<input value={bomNotes} onChange={e=>setBomNotes(e.target.value)} placeholder="Opsional"/></label></div>
      <div className="table-toolbar"><strong>Komponen Bahan</strong><button className="secondary-button compact" onClick={()=>setLines(rows=>[...rows,makeLine()])}><Plus size={15}/> Tambah Bahan</button></div>
      <div className="data-table-wrap"><table className="bom-grid"><thead><tr><th>#</th><th>Bahan</th><th>Qty</th><th>Satuan</th><th>Waste %</th><th>Qty Efektif</th><th></th></tr></thead><tbody>{lines.map((line,index)=>{const effective=Number(line.quantity||0)*(1+Number(line.wastePercent||0)/100);return <tr key={line.key}><td>{index+1}</td><td><SearchSelect value={line.componentItemId} options={itemOptions} placeholder="Cari bahan..." onChange={id=>chooseComponent(line,id)}/></td><td><input className="number-input" type="number" min="0" step="0.000001" value={line.quantity} onChange={e=>patchLine(line.key,{quantity:e.target.value})}/></td><td><select value={line.unitId} onChange={e=>patchLine(line.key,{unitId:e.target.value})}><option value="">—</option>{(context?.units||[]).map(x=><option key={x.id} value={x.id}>{x.code}</option>)}</select></td><td><input className="number-input" type="number" min="0" max="100" step="0.01" value={line.wastePercent} onChange={e=>patchLine(line.key,{wastePercent:e.target.value})}/></td><td><strong>{qty(effective)}</strong></td><td><button className="icon-button danger" disabled={lines.length===1} onClick={()=>setLines(rows=>rows.filter(x=>x.key!==line.key))}><Trash2 size={15}/></button></td></tr>;})}</tbody></table></div>
      <div className="bom-list"><div className="section-title"><div><span className="eyebrow">BOM AKTIF</span><h3>{bomType==='MENU'?'Menu':'Produksi / STJ'}</h3></div></div><div className="data-table-wrap"><table><thead><tr><th>Output</th><th>Standar</th><th>Bahan</th><th>Versi</th><th></th></tr></thead><tbody>{activeBoms.map(b=><tr key={b.id}><td><strong>{b.output_item_code}</strong><br/><span>{b.output_item_name}</span></td><td>{qty(b.output_quantity)} {b.output_unit_code}</td><td>{b.lines.length}</td><td>v{b.version}</td><td><div className="row-actions"><button className="secondary-button compact" onClick={()=>editBom(b)}>Edit</button><button className="icon-button danger" onClick={()=>void deactivateBom(b.id)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table>{!activeBoms.length&&<div className="empty-state"><Boxes size={34}/><strong>Belum ada BOM aktif</strong><span>Buat BOM pertama dari form di atas.</span></div>}</div></div>
    </section>

    <section className="section-card">
      <div className="section-title master-heading"><div><span className="eyebrow">PRODUKSI STJ</span><h3>Produksi / Central Kitchen</h3><p>Produksi mengurangi bahan berdasarkan snapshot BOM dan menambah stok hasil produksi dengan HPP aktual.</p></div><button className="primary-button compact" disabled={saving} onClick={saveProduction}><Factory size={16}/> Simpan Draft</button></div>
      <div className="production-grid"><label>Lokasi Produksi<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Pilih lokasi</option>{companyLocations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Tanggal<input type="date" value={productionDate} onChange={e=>setProductionDate(e.target.value)}/></label><label>BOM Produksi<select value={productionBomId} onChange={e=>{setProductionBomId(e.target.value);setActualOutput('');}}><option value="">Pilih BOM</option>{productionBoms.map(x=><option key={x.id} value={x.id}>{x.output_item_code} — {x.output_item_name}</option>)}</select></label><label>Jumlah Batch<input type="number" min="0" step="0.001" value={batchCount} onChange={e=>setBatchCount(e.target.value)}/></label><label>Hasil Aktual {selectedProductionBom?`(${selectedProductionBom.output_unit_code})`:''}<input type="number" min="0" step="0.000001" value={actualOutput} onChange={e=>setActualOutput(e.target.value)}/></label><label>Catatan<input value={productionNotes} onChange={e=>setProductionNotes(e.target.value)} placeholder="Opsional"/></label></div>
      {selectedProductionBom&&<div className="production-summary"><span>Hasil standar <strong>{qty(standardEntered)} {selectedProductionBom.output_unit_code}</strong></span><span>Yield sementara <strong>{yieldPreview?`${yieldPreview.toLocaleString('id-ID',{maximumFractionDigits:2})}%`:'—'}</strong></span><span>Bahan BOM <strong>{selectedProductionBom.lines.length} item</strong></span></div>}
      <div className="data-table-wrap"><table><thead><tr><th>No Produksi</th><th>Tanggal</th><th>Lokasi</th><th>Hasil</th><th>Batch</th><th>Standar</th><th>Aktual</th><th>Yield</th><th>Biaya</th><th>Status</th><th></th></tr></thead><tbody>{productions.map(row=><tr key={row.id}><td><strong>{row.transaction_number}</strong></td><td>{row.transaction_date?.slice(0,10)}</td><td>{row.location_name}</td><td>{row.output_item_name}</td><td>{qty(row.batch_count)}</td><td>{qty(row.standard_output)} {row.output_unit_code}</td><td>{qty(row.actual_output)} {row.output_unit_code}</td><td>{qty(row.yield_percent)}%</td><td>Rp{money(row.grand_total)}</td><td><span className={row.workflow_status==='FINANCE_VERIFIED'?'status-ok':'status-draft'}>{row.workflow_status==='FINANCE_VERIFIED'?'Finance Verified':'Draft'}</span></td><td>{canVerify&&row.workflow_status==='DRAFT'&&<button className="secondary-button compact" disabled={verifying===row.id} onClick={()=>void verifyProduction(row)}><ShieldCheck size={15}/>{verifying===row.id?'Memeriksa...':'Finance Verified'}</button>}</td></tr>)}</tbody></table>{!productions.length&&<div className="empty-state"><Factory size={34}/><strong>Belum ada produksi</strong><span>Buat transaksi produksi pertama setelah BOM Produksi tersedia.</span></div>}</div>
    </section>
  </div>;
}
