import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, PackageMinus, Plus, Save, ShieldCheck, Trash2 } from 'lucide-react';
import { api } from './api';

type Company={id:string;workspace_id:string;name:string};
type Location={id:string;company_id:string;name:string};
type Unit={id:string;workspace_id:string;code:string;name:string};
type Conversion={id:string;item_id:string|null;from_unit_id:string;to_unit_id:string;multiplier:string};
type CostCenter={id:string;company_id:string;name:string};
type BalanceItem={item_id:string;code:string;name:string;category_name:string;base_unit_id:string;base_unit_code:string;base_unit_name:string;quantity_on_hand:string;setup_ready:boolean};
type UsageLine={key:string;itemId:string;unitId:string;quantity:string;description:string;costCenterId:string};
type RecentRow={id:string;transaction_number:string;transaction_date:string;notes:string|null;grand_total:string;workflow_status:string;accounting_status:string;negative_stock_override:boolean;location_name:string;line_count:number};
type Shortage={lineId:string;lineNo:number;itemId:string;itemName:string;baseUnitCode:string;available:string;requested:string;after:string};

const today=()=>new Date().toISOString().slice(0,10);
const num=(value:string|number)=>Number(value||0);
const qty=(value:number)=>value.toLocaleString('id-ID',{maximumFractionDigits:3});
const money=(value:string|number)=>Number(value||0).toLocaleString('id-ID',{maximumFractionDigits:0});
const makeLine=():UsageLine=>({key:crypto.randomUUID(),itemId:'',unitId:'',quantity:'',description:'',costCenterId:''});

export function ClientItemUsage({canVerify,canOverride}:{canVerify:boolean;canOverride:boolean}){
  const [companies,setCompanies]=useState<Company[]>([]);const [locations,setLocations]=useState<Location[]>([]);const [units,setUnits]=useState<Unit[]>([]);const [conversions,setConversions]=useState<Conversion[]>([]);
  const [companyId,setCompanyId]=useState('');const [locationId,setLocationId]=useState('');const [date,setDate]=useState(today());const [notes,setNotes]=useState('');
  const [items,setItems]=useState<BalanceItem[]>([]);const [costCenters,setCostCenters]=useState<CostCenter[]>([]);const [lines,setLines]=useState<UsageLine[]>([makeLine()]);const [recent,setRecent]=useState<RecentRow[]>([]);
  const [saving,setSaving]=useState(false);const [verifying,setVerifying]=useState('');const [error,setError]=useState('');const [success,setSuccess]=useState('');
  const company=companies.find(x=>x.id===companyId);const companyLocations=locations.filter(x=>x.company_id===companyId);

  useEffect(()=>{void (async()=>{const [c,l]=await Promise.all([api<Company[]>('/api/master/companies'),api<Location[]>('/api/master/locations')]);setCompanies(c);setLocations(l);if(c[0])setCompanyId(c[0].id);})();},[]);
  useEffect(()=>{if(!company)return;void (async()=>{const [u,cv,cc,r]=await Promise.all([api<Unit[]>(`/api/master/units?workspaceId=${company.workspace_id}`),api<Conversion[]>(`/api/master/unit-conversions?workspaceId=${company.workspace_id}`),api<CostCenter[]>(`/api/master/cost-centers?companyId=${company.id}`),api<RecentRow[]>(`/api/client-transactions/item-usages?companyId=${company.id}`)]);setUnits(u);setConversions(cv);setCostCenters(cc);setRecent(r);setLocationId(current=>companyLocations.some(x=>x.id===current)?current:(companyLocations[0]?.id||''));})();},[companyId,company?.workspace_id,locations.length]);
  useEffect(()=>{if(!companyId||!locationId){setItems([]);return;}void refreshBalances();},[companyId,locationId]);

  async function refreshBalances(){setItems(await api<BalanceItem[]>(`/api/client-transactions/item-usage-balances?companyId=${companyId}&locationId=${locationId}`));}
  async function refreshRecent(){if(companyId)setRecent(await api<RecentRow[]>(`/api/client-transactions/item-usages?companyId=${companyId}`));}
  function itemOf(line:UsageLine){return items.find(x=>x.item_id===line.itemId);}
  function allowedUnits(line:UsageLine){const item=itemOf(line);if(!item)return[];const ids=new Set<string>([item.base_unit_id]);for(const c of conversions){if(c.to_unit_id===item.base_unit_id&&(c.item_id===item.item_id||c.item_id===null))ids.add(c.from_unit_id);}return units.filter(u=>ids.has(u.id));}
  function multiplier(line:UsageLine){const item=itemOf(line);if(!item||!line.unitId)return 0;if(line.unitId===item.base_unit_id)return 1;const specific=conversions.find(c=>c.item_id===item.item_id&&c.from_unit_id===line.unitId&&c.to_unit_id===item.base_unit_id);const general=conversions.find(c=>c.item_id===null&&c.from_unit_id===line.unitId&&c.to_unit_id===item.base_unit_id);return num((specific||general)?.multiplier||0);}
  function baseUsage(line:UsageLine){return num(line.quantity)*multiplier(line);}
  function balanceAfter(index:number){const line=lines[index],item=itemOf(line);if(!item)return 0;let used=0;for(let i=0;i<=index;i++){if(lines[i].itemId===line.itemId)used+=baseUsage(lines[i]);}return num(item.quantity_on_hand)-used;}
  const hasVisualShortage=useMemo(()=>lines.some((line,index)=>line.itemId&&num(line.quantity)>0&&balanceAfter(index)<0),[lines,items,conversions]);

  function updateLine(key:string,patch:Partial<UsageLine>){setLines(rows=>rows.map(row=>row.key===key?{...row,...patch}:row));}
  function selectItem(key:string,itemId:string){const item=items.find(x=>x.item_id===itemId);updateLine(key,{itemId,unitId:item?.base_unit_id||''});}
  function reset(){setNotes('');setLines([makeLine()]);}

  async function saveDraft(){setError('');setSuccess('');if(!companyId||!locationId)return setError('Company dan lokasi wajib dipilih.');if(lines.some(x=>!x.itemId||!x.unitId||num(x.quantity)<=0))return setError('Barang, qty dan satuan wajib diisi di setiap baris.');setSaving(true);try{const result=await api<{id:string;transaction_number:string}>('/api/client-transactions/item-usages',{method:'POST',body:JSON.stringify({companyId,locationId,transactionDate:date,notes:notes||null,lines:lines.map(x=>({itemId:x.itemId,unitId:x.unitId,quantity:num(x.quantity),description:x.description||null,costCenterId:x.costCenterId||null}))})});setSuccess(`${result.transaction_number} tersimpan sebagai draft. HPP akan dihitung otomatis saat Finance Verified.`);reset();await Promise.all([refreshRecent(),refreshBalances()]);}catch(err){setError(err instanceof Error?err.message:'Gagal menyimpan pemakaian barang');}finally{setSaving(false);}}

  async function verify(row:RecentRow){setError('');setSuccess('');setVerifying(row.id);try{const preview=await api<{shortages:Shortage[]}>(`/api/client-transactions/item-usages/${row.id}/preview`);let allowBelowZero=false;if(preview.shortages.length){const detail=preview.shortages.map(x=>`${x.itemName}: tersedia ${qty(num(x.available))} ${x.baseUnitCode}, setelah pemakaian ${qty(num(x.after))} ${x.baseUnitCode}`).join('\n');if(!canOverride){setError(`Stok tidak cukup. Finance Manager/Akuntakita perlu menyetujui pemakaian yang membuat saldo minus.\n${detail}`);return;}allowBelowZero=window.confirm(`Ada saldo barang yang akan menjadi minus:\n\n${detail}\n\nTetap Finance Verified?`);if(!allowBelowZero)return;}const result=await api<{total:string;shortages:Shortage[]}>(`/api/client-transactions/item-usages/${row.id}/verify`,{method:'POST',body:JSON.stringify({allowBelowZero})});setSuccess(result.shortages?.length?'Finance Verified dengan persetujuan saldo minus. HPP average dan draft jurnal sudah terbentuk.':'Finance Verified. HPP average, saldo barang dan draft jurnal sudah diperbarui.');await Promise.all([refreshRecent(),refreshBalances()]);}catch(err){const message=err instanceof Error?err.message:'Gagal verifikasi';setError(message.startsWith('MOVING_AVERAGE_NOT_AVAILABLE')?'HPP average belum tersedia untuk salah satu barang. Pastikan pernah ada pembelian/nilai persediaan sebelum pemakaian diverifikasi.':message);}finally{setVerifying('');}}

  return <div className="page-content item-usage-page"><section className="section-card">
    <div className="section-title master-heading"><div><span className="eyebrow">PERSEDIAAN</span><h3>Pemakaian Barang</h3><p>Tim client cukup isi barang dan qty. Nilai HPP diambil otomatis dari moving average saat Finance Verified.</p></div><button className="primary-button compact" onClick={saveDraft} disabled={saving}><Save size={16}/>{saving?'Menyimpan...':'Simpan Draft'}</button></div>
    <div className="helper-box"><strong>Kontrol saldo:</strong> sistem menampilkan stok sebelum dan perkiraan sisa. Jika akan minus, hanya Finance Manager atau Akuntakita yang dapat menyetujui saat verifikasi.</div>
    {success&&<div className="success-banner"><CheckCircle2 size={18}/><span>{success}</span></div>}{error&&<div className="form-error item-usage-error">{error}</div>}
    <div className="usage-header-grid"><label>Company<select value={companyId} onChange={e=>setCompanyId(e.target.value)}><option value="">Pilih company</option>{companies.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Lokasi<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Pilih lokasi</option>{companyLocations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Tanggal<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Catatan<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Opsional"/></label></div>
    <div className="usage-lines-head"><div><strong>Rincian Barang</strong><small>Harga/HPP tidak diinput client.</small></div><button type="button" className="secondary-button compact" onClick={()=>setLines(rows=>[...rows,makeLine()])}><Plus size={15}/> Tambah Baris</button></div>
    <div className="data-table-wrap"><table className="usage-table"><thead><tr><th>#</th><th>Barang</th><th>Stok Tersedia</th><th>Qty</th><th>Satuan</th><th>Perkiraan Sisa</th><th>Keperluan</th><th>Cost Center</th><th></th></tr></thead><tbody>{lines.map((line,index)=>{const item=itemOf(line),after=balanceAfter(index),warning=line.itemId&&num(line.quantity)>0&&after<0;return <tr key={line.key} className={warning?'usage-warning-row':''}><td>{index+1}</td><td><select value={line.itemId} onChange={e=>selectItem(line.key,e.target.value)}><option value="">Pilih barang</option>{items.map(x=><option key={x.item_id} value={x.item_id}>{x.name} · {x.category_name}</option>)}</select>{item&&!item.setup_ready&&<small className="setup-warning">Setup kategori oleh Akuntakita belum lengkap</small>}</td><td>{item?<><strong>{qty(num(item.quantity_on_hand))}</strong> {item.base_unit_code}</>:'—'}</td><td><input className="number-input" type="number" min="0" step="0.001" value={line.quantity} onChange={e=>updateLine(line.key,{quantity:e.target.value})}/></td><td><select value={line.unitId} onChange={e=>updateLine(line.key,{unitId:e.target.value})}><option value="">—</option>{allowedUnits(line).map(u=><option key={u.id} value={u.id}>{u.code}</option>)}</select></td><td className={warning?'usage-negative':''}>{item?<><strong>{qty(after)}</strong> {item.base_unit_code}{warning&&<small><AlertTriangle size={13}/> Akan minus</small>}</>:'—'}</td><td><input value={line.description} onChange={e=>updateLine(line.key,{description:e.target.value})} placeholder="Contoh: produksi harian"/></td><td><select value={line.costCenterId} onChange={e=>updateLine(line.key,{costCenterId:e.target.value})}><option value="">—</option>{costCenters.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></td><td><button type="button" className="icon-button danger" onClick={()=>setLines(rows=>rows.length===1?rows:rows.filter(x=>x.key!==line.key))}><Trash2 size={15}/></button></td></tr>;})}</tbody></table></div>
    {hasVisualShortage&&<div className="usage-warning-banner"><AlertTriangle size={18}/><div><strong>Ada barang yang perkiraan sisanya minus.</strong><span>Draft tetap bisa disimpan. Saat Finance Verified sistem akan meminta persetujuan user yang berhak.</span></div></div>}
  </section>
  <section className="section-card"><div className="section-title master-heading"><div><span className="eyebrow">KONTROL</span><h3>Pemakaian Terbaru</h3><p>Finance Verified mengurangi saldo barang dan membentuk jurnal HPP otomatis.</p></div></div><div className="data-table-wrap"><table><thead><tr><th>No Dokumen</th><th>Tanggal</th><th>Lokasi</th><th>Baris</th><th>Status</th><th>Nilai HPP</th><th></th></tr></thead><tbody>{recent.map(x=><tr key={x.id}><td><strong>{x.transaction_number}</strong>{x.negative_stock_override&&<small className="override-label"><AlertTriangle size={12}/> Override saldo minus</small>}</td><td>{x.transaction_date?.slice(0,10)}</td><td>{x.location_name}</td><td>{x.line_count}</td><td><span className={x.workflow_status==='FINANCE_VERIFIED'?'status-ok':'status-draft'}>{x.workflow_status==='FINANCE_VERIFIED'?'Finance Verified':'Draft'}</span></td><td>{x.workflow_status==='FINANCE_VERIFIED'?`Rp${money(x.grand_total)}`:'HPP otomatis'}</td><td>{canVerify&&x.workflow_status==='DRAFT'&&<button className="secondary-button compact" disabled={verifying===x.id} onClick={()=>verify(x)}><ShieldCheck size={15}/>{verifying===x.id?'Memeriksa...':'Finance Verified'}</button>}</td></tr>)}</tbody></table>{recent.length===0&&<div className="empty-state"><PackageMinus size={34}/><strong>Belum ada pemakaian barang</strong><span>Input pemakaian pertama dari form di atas.</span></div>}</div></section>
  </div>;
}
